# Generated by Django 3.1.1 on 2020-09-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0002_auto_20200927_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.PositiveIntegerField(max_length=10)),
                ('website', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
