# Generated by Django 3.1.1 on 2020-09-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0003_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.PositiveIntegerField(),
        ),
    ]
